@startuml encap
class  PurchaseRequestAuth{
    + auth(PurchaseRequest)
}

class PurchaseRequest{
    + amount
}

PurchaseRequestAuth ..> PurchaseRequest
PurchaseRequestAuth --> Handler 

interface Handler <<interface>> {
    + nextHandler: Handler
    + {abstract} isResponse(PurchaseRequest)
    + handle(PurchaseRequest)
}
Handler --> Handler
note left of Handler::handle
    if nextHandler != null:
        nextHandler.handle(PurchaseRequest)
end note

class BranchMangerHandler{
    + isResponse(PurchaseRequest)
    + handle(PurchaseRequest)
}

note right of BranchMangerHandler::isResponse
    isResponse(PurchaseRequest req) {
        if (req.amount < 25000) {
            handle()
        }    
        else {
            super.handl
        }
    }    
end note

/'
note right of PurchaseRequestAuth::auth
    auth(PurchaseRequest req) {
        if (req.amount < 25000) {
            dispatch to branch manager
        }    
        else if(req.amount < 100000){
            dispatch to regional director
        }
        else if(req.amount < 200000){
            dispatch to vice president
        }
        else if(req.amount < 400000){
            dispatch to president 
        }
    }    
end note
'/

class RegionalDirectorHandler {
    + isResponse(PurchaseRequest)
    + handle(PurchaseRequest)
}

class VicePresidentHandler {
    + isResponse(PurchaseRequest)
    + handle(PurchaseRequest)
}

class PresidentHandler {
    + isResponse(PurchaseRequest)
    + handle(PurchaseRequest)
}

Handler <|.. BranchMangerHandler
Handler <|.. RegionalDirectorHandler
Handler <|.. VicePresidentHandler
Handler <|.. PresidentHandler
@enduml